site_name: Facility Finder
site_description: |
  This is the 'Facility Finder' project website for CPSC 444.
repo_url: https://github.com/cynber/cs444-FacilityFinder
repo_name: cynber/cs444-FacilityFinder

# copyright: Copyright &copy; PLACEHOLDER
  # uncomment and change to add a copyright message

plugins:
  - search
  - glightbox
  # - social      # windows installation is failing, disable for now
  - blog:
      post_readtime: true
      archive: false
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - Guides:
    - Modify this site: ./About/contribute-to-this.md
    - Setup a new site:
      - Installation: ./About/setup-guide.md
      - Site Configuration: ./About/config-guide.md
      - Blog Setup: ./About/blog-setup-config.md

    - Credits: ./About/credits.md


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - sane_lists

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/cynber/cs444-FacilityFinder
    - icon: simple/rss
      link: /feed_rss_created.xml
      name: RSS
    # - icon: fontawesome/brands/youtube 
    #   link: https://example.com
    # - icon: fontawesome/brands/mastodon 
    #   link: https://example.com
    # - icon: fontawesome/brands/instagram 
    #   link: https://example.com
  generator: false  # set to false to hide the 'Generated with MkDocs' footer
