site_name: Facility Finder
site_description: |
  This is the 'Facility Finder' project website for CPSC 444.
# repo_url: https://github.com/cynber/cs444-FacilityFinder/
# repo_name: cynber/cs444-FacilityFinder

plugins:
  - git-revision-date-localized:
      type: custom
      custom_format: "Last updated: %B %d, %Y"
      fallback_to_build_date: true
      exclude:
        - index.md
        - blog/*
  - search
  # - privacy
  - glightbox
  # - social:
  #     cards_layout_options:
  #       font_family: Noto Sans
  #     enabled: !ENV [CI, false]
  - blog:
      post_readtime: true
      archive: false
      draft: true
      categories: true
      categories_name: Post Categories
      categories_allowed:
        - Project Update
        - CPSC 444

nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - Guides:
    - Modify this site: 
      - Overview: ./About/contribute-to-this.md
    - Setup a new site:
      - Installation: ./About/setup-guide.md
      - Site Configuration: ./About/config-guide.md
      - Blog Setup: ./About/blog-setup-config.md
  - About:
    - Credits: ./About/credits.md


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - sane_lists


theme:
  name: material
  language: en
  favicon: assets/img/droplet-solid.svg
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/droplet
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select


extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/cynber/cs444-FacilityFinder
  generator: false
