authors:
  felicia:
    name: Felicia
    description: Team Member
    avatar: https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Compass_-_Book_jacket_of_%22A_Treatise_on_Navigation_and_Nautical_Astronomy.%22.jpg/640px-Compass_-_Book_jacket_of_%22A_Treatise_on_Navigation_and_Nautical_Astronomy.%22.jpg
    # url: https://example.com
  kae:
    name: Kae-Rene
    description: Team Member
    avatar: https://cynber.github.io/cs444-FacilityFinder/assets/img/kae.jpg
    # url: https://example.com
  justin:
    name: Justin
    description: Team Member
    avatar: https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Compass_-_Book_jacket_of_%22A_Treatise_on_Navigation_and_Nautical_Astronomy.%22.jpg/640px-Compass_-_Book_jacket_of_%22A_Treatise_on_Navigation_and_Nautical_Astronomy.%22.jpg
    # url: https://example.com
  rafi:
    name: Rafi
    description: Team Member
    avatar: https://cynber.github.io/cs444-FacilityFinder/assets/img/rafi.jpg
    # url: https://example.com